### ISSUE TITLE
Error build in Arch Linux

### ISSUE THREAD

**Issue by samtux** [Wollac/qgis-snap#1]
I get the next error build in Arch Linux:

```
Snapcraft: building parts of /home/samtux/Descargas/qgis-snap/snapcraft.yaml

Snapcraft: Something went wrong. Maybe part is not defined in snapcraft.yaml
Suggestions: check syntax errors in yaml file.
Suggestion: This may happen due to internet connectivity issues.

Snapcraft returned with : Currently only `cleanbuild` will work on this system ('arch') 
```

The version the snapcraft is 2.3.0

**Comment by Wollac** [comment]
That is strange, maybe it has something to do with the AUR version of snapcraft. I couldn't reproduce this issue, as for me snapcraft on Arch was not working at all.
Nevertheless, I would strongly recommend to always build on a clean system. So, on Arch the easiest approach would be using docker, which also keeps your system clutter free:
 ```
docker pull snapcore/snapcraft
docker run -v $PWD:$PWD -w $PWD snapcore/snapcraft bash -c "apt update && apt upgrade -y && snapcraft clean && snapcraft"
``` 
I successfully verified this approach on my Arch machine: it compiles and you can then install/run it using `snapd` from the official repositories.
